language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t shilongjaycui/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true shilongjaycui/docker-react npm run test